// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macOS;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDummyWebApiKeyHere1234567890',
    appId: '1:1234567890:web:dummyappidweb',
    messagingSenderId: '1234567890',
    projectId: 'apple-music-ximena',
    authDomain: 'apple-music-ximena.firebaseapp.com',
    storageBucket: 'apple-music-ximena.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJTzlw1cgC9mis8YgzTz77WUfmzAgcsUs',
    appId: '1:83515133518:android:3b3de533b8c707b3c6fd1f',
    messagingSenderId: '83515133518',
    projectId: 'proyectofinal-4d22d',
    storageBucket: 'proyectofinal-4d22d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDummyIosApiKeyHere1234567890',
    appId: '1:1234567890:ios:dummyappiddios',
    messagingSenderId: '1234567890',
    projectId: 'apple-music-ximena',
    storageBucket: 'apple-music-ximena.appspot.com',
    iosBundleId: 'com.ximena.applemusic',
  );

  static const FirebaseOptions macOS = FirebaseOptions(
    apiKey: 'AIzaSyDummyMacOsApiKeyHere1234567890',
    appId: '1:1234567890:ios:dummyappiddmacos',
    messagingSenderId: '1234567890',
    projectId: 'apple-music-ximena',
    storageBucket: 'apple-music-ximena.appspot.com',
    iosBundleId: 'com.ximena.applemusic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDummyWindowsApiKeyHere1234567890',
    appId: '1:1234567890:windows:dummyappidwindows',
    messagingSenderId: '1234567890',
    projectId: 'apple-music-ximena',
    authDomain: 'apple-music-ximena.firebaseapp.com',
    storageBucket: 'apple-music-ximena.appspot.com',
  );
}
